---
- name: Creating the MySQL dumping cron job
  ansible.builtin.cron:
    name: "Dumping MySQL db"
    weekday: "{{ cr_weekday }}"
    hour: "{{ cr_hour }}"
    minute: "{{ cr_minute }}"
    job: "mysqldump -u {{ mysql_username }} -p {{ mysql_passwd }} {{ mysql_database }} > {{ mysql_dump}}"
